trigger:
- main

pool:
 name: Default
 vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds

variables:
 imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
   repository: $(imageName)
   command: build
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
   Dockerfile: app/Dockerfile
